// <auto-generated />
namespace DA2_SistemaEscolar2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CamposRequeridosAlumnos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamposRequeridosAlumnos));
        
        string IMigrationMetadata.Id
        {
            get { return "201609201540458_CamposRequeridosAlumnos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
